<?php

/**
 * @file
 * Contains message_auto_notify.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\message_notify\Plugin\Notifier\Manager;

/**
 * Implements hook_help().
 */
function message_auto_notify_help($route_name, RouteMatchInterface $route_match): ?string {
  $output = NULL;
  // Main module help for the message_auto_notify module.
  if ($route_name == 'help.page.message_auto_notify') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Automatically notify users when a new message is created.') . '</p>';
  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function message_auto_notify_theme(): array {
  return [
    'message_auto_notify' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @throws Exception
 */
function message_auto_notify_entity_insert(Drupal\Core\Entity\EntityInterface $entity): void {
  if ($entity instanceof \Drupal\message\Entity\Message) {
    // Send notifications base on the settings.
    /** @var \Drupal\message_auto_notify\Entity\Notification[] $notifications */
    $notifications = \Drupal\message_auto_notify\Entity\Notification::loadMultiple();
    /** @var Manager $notifierManager */
    $notifierManager = \Drupal::getContainer()->get('plugin.message_notify.notifier.manager');
    foreach ($notifications as $notification) {
      // Check if the user has closed the notification.
      /** @var \Drupal\message_auto_notify\UserNotifySettingManagerInterface $user_notify_setting_manager */
      $user_notify_setting_manager = \Drupal::service('message_auto_notify.user_notify_setting');
      $user_setting = $user_notify_setting_manager->getSetting($entity->getOwnerId());
      $user_closed_notify = false;
      if (isset($user_setting[$notification->id()]) && $user_setting[$notification->id()] === false) $user_closed_notify = true;

      if (!$user_closed_notify &&
        $notification->getTemplate() === $entity->bundle() &&
        $notifierManager->hasDefinition($notification->getNotifier())) {
        try {
          /** @var \Drupal\message_notify\Plugin\Notifier\MessageNotifierInterface $notifier */
          $notifier = $notifierManager->createInstance($notification->getNotifier(), [
            'notification' => $notification
          ], $entity);
          $notifier->send();
        } catch (\Exception $exception) {
          \Drupal::logger('message_auto_notify')->error('Notification fails to send! Notifier is ' . $notification->getNotifier() . ', message is '. $entity->id().', error: '.$exception->getMessage());
        }
      }
    }
  }
}


/**
 * Implements hook_entity_base_field_info().
 */
function message_auto_notify_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];

  if ($entity_type->id() == 'message') {
    $fields['message_link'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Business link of the message'))
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'inline',
        'type' => 'string'
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield'
      ])
      ->setDisplayConfigurable('view', true)
      ->setDisplayConfigurable('form', true);

    $fields['phone'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Phone number'))
      ->setDescription('If this is not set, notifier will try to use the phone of the user.')
      ->setDisplayOptions('view', [
        'label' => 'inline',
        'type' => 'string'
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield'
      ])
      ->setDisplayConfigurable('view', true)
      ->setDisplayConfigurable('form', true);
  }

  return $fields;
}
