message_auto_notify.settings:
  type: config_object
  label: 'Settings of message_auto_notify module'
  mapping:
    wechat_notifier_wechat_connect_app:
      type: string
      label: 'Wechat connect application for wechat notifier'

message_auto_notify.notification.*:
  type: config_entity
  label: 'Notification config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    template:
      type: string
      label: 'Template'
    notifier:
      type: string
      label: 'Notifier id'
    use_remote_template:
      type: bool
      label: 'Use remote template'
    remote_template:
      type: string
      label: 'Remote template'
